import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/header";
import { StoreProvider } from "@/core/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="dark h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <Header />

          <main className="flex-1">
            {children}
          </main>
        </StoreProvider>
      </body>
    </html>
  );
}
